spring.application.name=camel-le4
server.port=8081
camel.springboot.main-run-controller=true
logging.level.org.apache.camel=INFO

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

camel.component.kafka.brokers=localhost:9094
camel.component.kafka.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer
camel.component.kafka.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
camel.component.kafka.key-serializer=org.apache.kafka.common.serialization.StringSerializer
camel.component.kafka.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Actuator / Prometheus
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.enabled=true